web: gunicorn backend.wsgi --chdir backend --limit-request-line 8188 --log-file -
worker: REMAP_SIGTERM=SIGQUIT celery --workdir backend --app=backend worker --loglevel=info
beat: REMAP_SIGTERM=SIGQUIT celery --workdir backend --app=backend beat -S redbeat.RedBeatScheduler --loglevel=info
